### ISSUE TITLE
Separate formatting for different levels of headers

### ISSUE THREAD

**Issue by michal2274** [cqroot/joplin-outline#103]
First of all, I apologize if this is the wrong place for this

I'd like to bold first level of headings (e.g. 1. Main topic), but not the rest (1.1 Subtopic).
Is there any way to achieve that in the outline.css? I can't see any way of targetting only the first level of headings

**Comment by jillpouchain** [comment]
Hey !

Yes, there is: each heading has a class corresponding to its level. So `h1` has a class `toc-item-1`, `h2` has a class `toc-item-2`, ... So if you only want the first level of headings you can just add a `a.toc-item-1` in your `outline.css` file.

Example:
```css
div.outline-content {
  a.toc-item-1 {
    color: red;
    font-weight: 900;
  }
  a.toc-item-2 {
    color: blue;
    font-weight: 400;
  }
}
```

![Image](https://github.com/user-attachments/assets/9347587d-cb51-4706-91c7-9c6d61583462)
