### ISSUE TITLE
suggest: backgroud-color when hovering

### ISSUE THREAD

**Issue by rexlevin** [cqroot/joplin-outline#57]
please add a light gray background color when hovering, it's more obvious
thanks

**Comment by cqroot** [comment]
https://github.com/cqroot/joplin-outline/wiki/Custom-panel-style

You can add the following content to the User Style of the advanced settings.

```css
.toc-item-link:hover {
  background-color: #f0f0f0;
}
```
