### ISSUE TITLE
[Suggestion] Can change "OUTLINE" title of the sidebar

### ISSUE THREAD

**Issue by Fr3d-P** [cqroot/joplin-outline#92]
The sidebar is always named "OUTLINE".
I can't see any way to change it to another text (like "TOC", or to translate it in another language).

This option could be great in outline's settings panel

**Comment by jillpouchain** [comment]
Hey there,
This issue is a bit old, but I was also interested in this enhancement. I found a solution using CSS: it might not be the cleanest approach, but it works for now. Here's the code I added to the `outline.css` file:

```css
div.outline-content {
  #header {
    visibility: hidden;
    &::after {
      content: 'Table of content';
      visibility: visible;
      color: blue;
    }
  }
}
```

And here's a screenshot:

![Image](https://github.com/user-attachments/assets/47f0c9e9-b606-4059-b63c-024c4f0546a4)
